### ISSUE TITLE
Create Class diagram of ER schema

### ISSUE THREAD

**Issue by SirriCelles** [SirriCelles/EAMS_Service#3]
- [x] #6
- [x] create a well represented class diagram representing the ER schema, relationships, attributes and methods

- [x] upload schema to a shared google drive folder for project assets

**Comment by SirriCelles** [comment]
> * [x]  [share  a collaborative  lucid Chart class diagram for collaborators to  work on the class diagram #6](https://github.com/SirriCelles/EAMS_Service/issues/6)
> * [x]  create a well represented class diagram representing the ER schema, relationships, attributes and methods
> * [x]  upload schema to a shared google drive folder for project assets

completed

**Comment by Nasah-Kuma** [comment]
@SirriCelles please share a link to the lucichart doc as a comment to close this issue.

**Comment by Nasah-Kuma** [comment]
> 

I thought it will be good we add the link to the lucichart doc for easy access in case of any updates <https://lucid.app/lucidchart/9fb22caa-c4ac-4044-82a8-67acf35dbf74/edit?page=HWEp-vi-RSFO&invitationId=inv_1629ddbd-e031-4a93-a0ff-21ae8267b1a3#>
